### PR TITLE
Added convenient methods. This are taken from the Android SDK, hence …

### PR DESCRIPTION
**Pull request by thelong1EU**
…the license notice. It is an alternative to the plain old SQLite RAW Statements.

### CODE REVIEW

**Comment by alextekartik** [comment]
I like the suggestions and actually the first API I had in mind was more along the line of the SQLiteDatabase API of Android similar to what you did (SQFliteHelper for insert/update/delete). Do you mind if I take some time to review and maybe split your code. SQLiteQueryBuilder could definitely be an helper on its own. Not sure for exemple if SQFliteHelper should be a singleton. Also I would create some usage example in the example application, some unit tests (for SQLiteQueryBuilder) and maybe change some naming convention to be more dartish (constant are not typically uppercase in dart)

**Comment by thelong1EU** [comment]
Not ar all.

**Comment by thelong1EU** [comment]
If you like we could split the work.

**Comment by alextekartik** [comment]
I ported some of your suggestions, thanks, breaking compatibility with the existing (it is still an experiment). Basically the old commands (query/update/insert/delete) now have the prefix raw and the new commands allow using convenient parameters. I added some unit tests and the example project has a basic Todo table using the new helpers

**Comment by thelong1EU** [comment]
Perfect!

**Pull request closed without merging**
