### PR TITLE
Stopped blocking the main thread for `[FMDBDatabaseQueue close]`.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/tekartik/sqflite/issues/809

### CODE REVIEW

**Comment by gaaclarke** [comment]
@alextekartik, looks like you don't have CI setup.  Let me know what you want in terms of testing.

So this works, but it isn't as efficient as if we edited [FMDBDatabaseQueue close].  If we did that we could eliminate a dispatch_sync call and not have to worry about them breaking us if they change that method.

**Comment by alextekartik** [comment]
Thanks for tackling this.

I have github actions running on the 3 platforms:
https://github.com/tekartik/sqflite/actions

but I could not manage to setup integration test yet in the CI but there are some that I run manually (don't remember how right now) so yes the native plugin code is not tested automatically (yet)

The example app is what I use in terms of testing too.
Note that the Mac code is a copy of the the iOS one (but don't worry about that yet, I'll manage later).

I think a case is missing when the database is not opened for deleting the database file (the example app should report this error, and if not, I'll add one test)

> So this works, but it isn't as efficient as if we edited [FMDBDatabaseQueue close]. 

It is hard to know whether FMDB is still maintained and whether it is the right choice to stick with it. I'm not an iOS expert, don't have a M1 nor time to look for a better implementation but at some point we might get rid of it (or fork it).

I don't think performance is crucial here (i.e. most people never call it) and if you notice the UI thread being blocked before, it is likely that close is doing some heavy stuff. Thanks again.

**Comment by gaaclarke** [comment]
@alextekartik were you able to test the change?  I never got a chance to test it and was planning on coming back around to it.  I found that it isn't as high priority as I thought since my microbenchmark was artificially causing the connection to close more frequently than would happen in regular usage.

**Comment by gaaclarke** [comment]
Okay, I just wanted to make sure we didn't accidentally publish the change without having tested it first.

**Comment by alextekartik** [comment]
So I changed several things. One tricky part is deleting the database while in use (in this case it closes the database first). I think I have handled all the cases (run_integration_test can be used on iOS for some native testing).

Fixed in 2.0.3-dev.1 published. Thanks again for the report and tacking this issue! Let me know if that works for you and I'll publish a 2.0.3 stable version later.

**Pull request merged**
