### PR TITLE
Dropped the extra thread hop when calling results

### PR DESCRIPTION
**Pull request by gaaclarke**
It's [no longer required](https://docs.flutter.dev/development/platform-integration/platform-channels?tab=type-mappings-kotlin-tab#channels-and-platform-threading) with Flutter 3.0 for iOS and Android.

### CODE REVIEW

**Comment by gaaclarke** [comment]
Oops, i edited macos instead of iOS.  I'll fix that.

**Comment by gaaclarke** [comment]
> Oops, i edited macos instead of iOS. I'll fix that.

Done.

**Comment by alextekartik** [comment]
Good, I was not aware of that. I think I have a unit test  (https://github.com/tekartik/sqflite/blob/master/sqflite/test/sqflite_macos_impl_test.dart) that ensure that iOS and MacOS implementation are the same (I also have a script https://github.com/tekartik/sqflite/blob/master/sqflite_support/tool/copy_ios_code_to_macos.dart that copy the code) which will likely fail (did you run flutter test?). I might add a (hopefully not too ugly) way to make it compatible for both? (using Platform.isIOS for example).

**Comment by alextekartik** [comment]
Good and thanks!, I was not aware of that. I think I have a unit test  (https://github.com/tekartik/sqflite/blob/master/sqflite/test/sqflite_macos_impl_test.dart) that ensure that iOS and MacOS implementation are the same (I also have a script https://github.com/tekartik/sqflite/blob/master/sqflite_support/tool/copy_ios_code_to_macos.dart that copy the code) which will likely fail (did you run flutter test?). Good if you could add a way to make it compatible for both? (likely using `#if TARGET_OS_IPHONE`). Otherwise I will tackle it later.

**Review by alextekartik — APPROVED** [review]
Excellent! Thanks for handling this constraint (but hopefully it is easier to maintain for both)

**Pull request merged**
