### PR TITLE
Update sqflite.dart

### PR DESCRIPTION
**Pull request by dubey2k**
import statement was included two times..

### CODE REVIEW

**Comment by dubey2k** [comment]
import statement was included twice

**Comment by alextekartik** [comment]
Thanks for catching this!

**Comment by dubey2k** [comment]
> Thanks for catching this!

Yup 😊

**Comment by alextekartik** [comment]
It was actually wrong...That was an export statement (needed) not an import. The project does not compile with your change I wonder why github/travis did not warn me. Reverted!

**Comment by dubey2k** [comment]
Oh I am so sry man.. i missed it...

**Pull request merged**
