### PR TITLE
FFI init optional callback for overriding sqlite3 dynamic opening from within the isolate

### PR DESCRIPTION
**Pull request by davidmartos96**
Fixes: #551 

@alextekartik Please let me know if you would like to move something around or rename the method/typedef. I don't have much experience with stub imports in Dart.
Should the docstring be repeated for the stub file and for the io file?

### CODE REVIEW

**Comment by alextekartik** [comment]
That looks great @davidmartos96 

I will likely merge (I'll wait for the travis/github actions check first) and do more check afterwards ;)

If you can, before:
- rename `FFIInit` typedef to `SqfliteFfiInit` (Ffi instead of FFI for consistency with what we have so far and Sqflite prefix as I don't want to pollute the main namespace more than I do now)
- yes you can remove the comment in the stub file (and keep it in io)

Thanks for using the nnbd_safety branch too!

**Review by alextekartik — COMMENTED** [review]
Perfect!

**Comment by davidmartos96** [comment]
@alextekartik Ok, sound great!
Please let me know if you need anything else.

**Comment by alextekartik** [comment]
Version `2.0.0-nullsafety.2` published "as-is" with your change. (Somehow the formatting made some minor changes).
Thanks again for tackling this.

**Comment by alextekartik** [comment]
Version `2.0.0-nullsafety.3` published to allow compiling on the web (even if does not work). Some people just import everything (conditional imports are painful to setup) and perform check at runtime to choose the correct factory so I moved the SqfliteFfiInit in a safe place.

It fixes travis build: https://travis-ci.org/github/tekartik/sqflite/builds/745866251

**Pull request merged**
