### PR TITLE
Fix StandardMethodCodec symbol

### PR DESCRIPTION
**Pull request by jiahaog**
There was an issue with the symbol names, sorry for the trouble!

### CODE REVIEW

**Comment by jiahaog** [comment]
cc @gaaclarke

**Review by gaaclarke — APPROVED** [review]
LGTM.  I don't know what I did to mess this up.  I just tested it locally too and it looks good.  We should really get CI setup for this repo.  At a minimum just to compile everything.  Sorry I didn't catch it @alextekartik.

**Comment by alextekartik** [comment]
Thanks for the follow up @jiahaog 
Lesson learned: never publish native changes without running at least once.

I published v2.0.3-dev.5

> We should really get CI setup for this repo. At a minimum just to compile everything.

I would need some help on what is needed in a github actions to at least be able to run:
```
flutter build ios --no-codesign
flutter build macos
```

(and even better run some integration tests).
In another note, since I don't have a Mac M1 to test, does it work on this platform target (macOS arm)? I don't know how much FMDB is supported in the long term and whether it works for the macos arm target.

**Comment by lisong996** [comment]
Mac M1 is not working

**Pull request merged**
